filebeat.inputs:
  - type: log
    enabled: true
    paths:
      - /home/vboxuser/lab-siem/suricata-logs/eve.json
    json.keys_under_root: true
    json.add_error_key: true
    json.message_key: log

output.elasticsearch:
  hosts: ["http://localhost:9200"]

setup.kibana:
  host: "http://localhost:5601"
